### ISSUE TITLE
Try Azure Functions

### ISSUE THREAD

**Issue by paulbatum** [projectkudu/TryAppService#19]
Would be great to have an experience that allows customers to try functions with just a microsoft account.

Additional notes:

> Under the current plan, a user doing the 1-hour free trial would be able to attempt resource creation. For example, they could choose a Notification Hubs binding and attempt to create a hub to go with it.
> 
> We should mark templates and bindings which would need creations. The user should not be able to attempt these actions and then run into RBAC errors.
> 
> We need to discuss what happens to a marked item. We could remove it, or we could disable it but keep it visible.

(from https://github.com/projectkudu/AzureFunctions/issues/86)

**Comment by ahmelsayed** [comment]
note that the actual work for this is almost 90% complete in bb0d6185151da0c44dec9372bd6789fe5d883229, 7a02709ae832f2bf07b45c64ed84ebb759bf9267 and 8e4d2e1916c83432eaaa069116cbb569a5bcd0c6.
The only missing part is monitoring.

**Comment by fashaikh** [comment]
Deployed.
