### ISSUE TITLE
[Mobile] Android client should be updated to the latest version

### ISSUE THREAD

**Issue by lindydonna** [projectkudu/TryAppService#21]

**Comment by alecouteurbisson** [comment]
I have managed to get the Android client to work by editing the site config to include
`<add key="MS_SkipVersionCheck" value="true" />`
in the appSettings.  It's a bit of a faff but it is working correctly on the Nexus 5X emulator.

**Comment by lindydonna** [comment]
@alecouteurbisson A better fix would be to use the the [Azure Mobile Apps Android library](https://bintray.com/microsoftazuremobile/SDK/Mobile-Apps-Android/3.1.0). In gradle: `compile 'com.microsoft.azure:azure-mobile-android:3.1.0'`.
