### ISSUE TITLE
Azure Web App Creation Failure - ASP.Net MVC 5 With Entity Framework

### ISSUE THREAD

**Issue by fmorriso** [projectkudu/TryAppService#25]
After logging into my Azure account, when I visit https://tryappservice.azure.com/en-us, select ASP.Net MVC 5 With Entity Framework, and click the Create button, I see the following error on the screen:

No free resources are available currently. Please try again later.

I tried several times, but each time resulted in the same error.

What can I do to get past this error?

**Comment by fashaikh** [comment]
This can happen in two situations
1) There can be a downtime 30 sec - 1 min .. when the application is being deployed and resources are getting loaded in memory. We are working on a redesign that will allow load balancing in this scenario.
2) There are a lot of user and our free resources are all assigned.  This has been mitigated by adding more subscriptions and hence resources into the pool
