### ISSUE TITLE
0 Free Websites

### ISSUE THREAD

**Issue by davetheriault** [projectkudu/TryAppService#26]
The site touts "Host 10 ASP.NET websites for free with Azure App Service. Secure, reliable, and business-ready in seconds. Start for free and scale as your traffic grows."

But the reality is:
"No free resources are available currently. Please try again later."

**Comment by fashaikh** [comment]
@davetheriault . Sorry about the late response, and the confusion in the links. We are taking your feedback into consideration. 

For the 10 free websites you need to create a free account using the link below the green button which leads you to https://azure.microsoft.com/en-us/free/  , which requires a credit card (no charges) and a microsoft account.

The green button is for our TryAppservice project, which allows you to quickly get a free website using your social identity. 

The `No free resources` error can happen in two situations :
1) There can be a downtime 30 sec - 1 min .. when the application is being deployed and resources are getting loaded in memory. We are working on a redesign that will allow load balancing in this scenario.
2) There are a lot of user and our free resources are all assigned. This has been mitigated by adding more subscriptions and hence resources into the pool
