### ISSUE TITLE
Nothing appears after publishing web app (free site for 24 hours)

### ISSUE THREAD

**Issue by JohnyL** [projectkudu/TryAppService#27]
I've created free 24 hours Azure app (ASP.NET Core), but browser shows empty screen.

**Comment by davidebbo** [comment]
Can you clarify how you created the app? ASP.NET Core is not currently an option on https://tryappservice.azure.com/

**Comment by JohnyL** [comment]
File -> New Project -> ASP.NET Core Web Application (.NET Framework) -> Build -> Publsh WebApplication1. So, I publish this app as it is, i.e. I did no changes to it. I import the profile which was given to me and published it. Then run the given URL => empty browser window.

**Comment by davidebbo** [comment]
Can you share your site name to help investigation? Thanks.

**Comment by JohnyL** [comment]
http://d1abf02f-0ee0-4-231-b9ee.azurewebsites.net

**Comment by davidebbo** [comment]
If you use Kudu Console to look at the files, there is a log with detailed errors in d:\home\logfiles. Here is a piece of it:

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Unable to resolve service for type 'BonusApp.Data.ApplicationDbContext' while attempting to activate 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`3[BonusApp.Models.ApplicationUser,Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRole,BonusApp.Data.ApplicationDbContext]'.
System.InvalidOperationException: Unable to resolve service for type 'BonusApp.Data.ApplicationDbContext' while attempting to activate 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`3[BonusApp.Models.ApplicationUser,Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRole,BonusApp.Data.ApplicationDbContext]'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
```

Note that this is likely not tryappservice specific, but probably something you'd see as well on a regular Azure Web App.

**Comment by fashaikh** [comment]
@JohnyL  Closing the issue. Feel free to reopen if this is still relevant
