### ISSUE TITLE
As informações se contradizem e simplesmente não funciona

### ISSUE THREAD

**Issue by ricardops05** [projectkudu/TryAppService#30]
Primeiro mostra a mensagem "...Seja nosso convidado por até uma hora para a experiência do Serviço de Aplicativo do Azure sem assinatura do Azure, gratuitamente e sem compromisso. "
Quando chego na etapa 2 para Criar o aplicativo é apresentada a mensagem "Não há recursos gratuitos disponíveis atualmente. Tente novamente mais tarde." As informações estão se contradizendo.

**Comment by davidebbo** [comment]
There was a capacity issue that was causing this, but it should be ok now. Could you please try again?
