### ISSUE TITLE
what was the next step?

### ISSUE THREAD

**Issue by nivaas2k3** [projectkudu/TryAppService#32]
i am new to azure mobile apps development and i created one free app and got message like its created successfully http://98c43610-0ee0-4-231-b9ee.azurewebsites.net/
what was the new step ?

**Comment by fashaikh** [comment]
Sorry about the late response. You can download and run the clients provided . They talk with the backend mobile app that was created.
You can read more about it here https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-value-prop/ . Feel free to create another mobile app if you need to explore further..
