### ISSUE TITLE
Dont set FUNCTIONS_EXTENSION_VERSION for all sites

### ISSUE THREAD

**Issue by ahmelsayed** [projectkudu/TryAppService#42]
in both load() and create() this is set for all sites, this is not correct.

**Comment by fashaikh** [comment]
I have a fix for this now with 619987b  . Existing sites created still have the bad FUNCTIONS_EXTENSION_VERSION. Will need to do a bit more work before closing this.

**Comment by fashaikh** [comment]
This was fixed in https://github.com/projectkudu/TryAppService/commit/619987b76c2ccd3c65392f358d7fc274525598c3
