### ISSUE TITLE
Host 10 Websites for Free on Azure App Service

### ISSUE THREAD

**Issue by tylerhuynh** [projectkudu/TryAppService#61]
Why is my site expires within 24 hours after I signed up for the Azure already?  How can I host the website w/o being expired in 24 hours?
Asure Account: tylerhuynh99@live.com

![azure free 10 websites with azureappservice](https://cloud.githubusercontent.com/assets/11162788/19303912/28dfe62c-9030-11e6-8075-0b894b11ee56.JPG)

https://6d06fb39-0ee0-4-231-b9ee.azurewebsites.net/

Thanks,
Tyler
972-523-7112

**Comment by fashaikh** [comment]
This link was for a limited free trial of Azure Appservice and is for 1-24 hrs only.
To create sites with no expiry, you need to sign up for  a free azure account , using this link https://azure.microsoft.com/free/
