### ISSUE TITLE
Try Functions

### ISSUE THREAD

**Issue by Kyle-1** [projectkudu/TryAppService#71]
Went to functions.azure.com and selected webhook + api with Javascript.

Using the default provided I opened the logs window and clicked on the Run button ... no response at all. Simplified the javascript to just log something, saved and hit Run ... nothing.

The 1 hour demo timed out leaving an endless loop - select Functions > try Functions > select web hook with javascript > Create this function > sign in with microsoft > back to the beginning > select Functions > try Functions > ...

Not clear if this is because:
* the trial capability is broken
* using a mac - Safari or Chrome
* I have an existing azure account

**Comment by fashaikh** [comment]
Sorry about the late response. This may be interesting to investigate. I havent been able to repro it.
If this still reproes could you reply back. If not I'll close this issue in a week

**Comment by fashaikh** [comment]
![uDSGNMdHVL](https://user-images.githubusercontent.com/2650941/54626743-09369080-4a2f-11e9-9125-5606977fdc85.gif)
Shoudl be fixed now
