### ISSUE TITLE
Add basic ARM support to tryappservice.azure.com

### ISSUE THREAD

**Issue by ehamai** [projectkudu/TryAppService#79]
For Try-functions, we have a lot of code that relies on ARM requests.  For now we fake out those requests so that we don't have a bunch of if/else logic for Try-Function scenario's which would destabilize our mainline scenario's. 

Since tryappservice.azure.com has ARM access to every temporary resource group, it sounds like a better long-term approach would be to add an ARM pass-thru API so that we could use real data and not have to fake our calls out.  I think the rules for that API could look like this:

1.	Allow all GET requests through under the resource group for the owning user.
2.	Allow PUT/POST requests for the appsettings API (It might actually be okay to allow this for everything under a site, not including the site itself, but it might be better to start-off restrictive)

And if we keep the interface of the pass-through API really generic, it should be pretty simple.  Maybe something like this:

POST request to /api/arm:
{
   uri : “/subscrpitions/<sub>/resourceGroups/<rg>/providers/Microsoft.web/sites/<siteName>/config/appsettings/list?api-version=<version>”,
   method: “POST”
}

**Comment by fashaikh** [comment]
tryfunctions experience has been forked and this is nto needed anymore
