### ISSUE TITLE
Functions free trial signup loop

### ISSUE THREAD

**Issue by pierluigi** [projectkudu/TryAppService#87]
When I try to use the service to test run a function for 1 hour I end up in a loop. 

Here's what I'm doing:
1. Visit https://tryfunctions.com/ng-min/try?trial=true
2. Select "Webhook + API" & "Javascript"
3. Click "Create this function", pick GitHub as authentication provider 
4. Authorize app
5. I'm redirected to https://tryappservice.azure.com where if I select "Function App" from the list, I start again from step 1

Please see the video recording for more info:

![out](https://user-images.githubusercontent.com/1078545/46018632-3afb1a00-c0d2-11e8-9120-76b93dec003f.gif)

**Comment by fashaikh** [comment]
This would happen if you already had a trial app from try app service and then tried to get a free function app in the same experience/browser session.  We have revamped the experience and plan to make more changes soon for tryfunctions.  Sorry about the delay in addressing this, and thanks for reporting the issue.


![uDSGNMdHVL](https://user-images.githubusercontent.com/2650941/54626126-cfb15580-4a2d-11e9-9337-ba2a48d24c37.gif)
